const STORAGE_KEY='mujeeb-pilot-orders-v1';
const seedOrders=[
  {id:'MJ-1058',customer:'نورة العتيبي',phone:'+966 5X XXX 2184',value:349,status:'confirmed',updated:'منذ 4 دقائق',attempts:1},
  {id:'MJ-1057',customer:'محمد الشهري',phone:'+966 5X XXX 7721',value:185,status:'cancelled',updated:'منذ 12 دقيقة',attempts:1},
  {id:'MJ-1056',customer:'سارة القحطاني',phone:'+966 5X XXX 4983',value:520,status:'human_follow_up',updated:'منذ 26 دقيقة',attempts:1},
  {id:'MJ-1055',customer:'عبدالله الحربي',phone:'+966 5X XXX 6219',value:275,status:'confirmed',updated:'منذ 41 دقيقة',attempts:1},
  {id:'MJ-1054',customer:'ريم الدوسري',phone:'+966 5X XXX 3560',value:430,status:'queued',updated:'اليوم، 15:20',attempts:0},
  {id:'MJ-1053',customer:'خالد المطيري',phone:'+966 5X XXX 9074',value:199,status:'queued',updated:'اليوم، 15:14',attempts:0},
  {id:'MJ-1052',customer:'لطيفة الزهراني',phone:'+966 5X XXX 1185',value:610,status:'confirmed',updated:'اليوم، 14:52',attempts:1},
  {id:'MJ-1051',customer:'فهد الغامدي',phone:'+966 5X XXX 8042',value:145,status:'queued',updated:'اليوم، 14:33',attempts:0}
];
let orders=loadOrders();let selectedOrderId=null;
const labels={queued:'بانتظار الاتصال',calling:'جاري الاتصال',confirmed:'مؤكد',cancelled:'ملغي',human_follow_up:'متابعة بشرية'};
function loadOrders(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||seedOrders}catch{return seedOrders}}
function saveOrders(){localStorage.setItem(STORAGE_KEY,JSON.stringify(orders))}
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function setView(view){$$('.view').forEach(v=>v.classList.remove('active'));$$('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===view));$(`#${view}View`).classList.add('active');$('#viewTitle').textContent={dashboard:'نظرة عامة',orders:'الطلبات',calls:'مركز الاتصال'}[view];$('.sidebar').classList.remove('open');renderAll()}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$$('[data-view-target]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.viewTarget)));$('#mobileMenu').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));
function statusBadge(status){return `<span class="status status-${status}">${labels[status]}</span>`}
function metrics(){const attempted=orders.filter(o=>o.attempts>0).length,confirmed=orders.filter(o=>o.status==='confirmed').length,cancelled=orders.filter(o=>o.status==='cancelled').length,follow=orders.filter(o=>o.status==='human_follow_up').length;return{attempted,confirmed,cancelled,follow,queued:orders.filter(o=>o.status==='queued').length}}
function renderMetrics(){const m=metrics();$('#metrics').innerHTML=[['محاولات الاتصال',m.attempted,'◉','من أصل 50 في التجربة'],['طلبات مؤكدة',m.confirmed,'✓','جاهزة للتجهيز'],['طلبات ملغاة',m.cancelled,'×','قبل دفع تكلفة الشحن'],['متابعة بشرية',m.follow,'↗','تحتاج تدخل الفريق']].map(x=>`<article class="metric"><div class="metric-head"><span>${x[0]}</span><i class="metric-icon">${x[2]}</i></div><strong>${x[1]}</strong><small>${x[3]}</small></article>`).join('');const totalDone=m.confirmed+m.cancelled+m.follow;const rate=m.attempted?Math.round(totalDone/m.attempted*100):0;$('#completionRate').textContent=`${rate}%`;$('#donutLabel').textContent=totalDone;const denom=Math.max(totalDone,1),a=m.confirmed/denom*100,b=m.cancelled/denom*100;$('#donut').style.background=`conic-gradient(var(--green) 0 ${a}%,var(--red) ${a}% ${a+b}%,#dba558 ${a+b}% 100%)`;$('#legend').innerHTML=[[m.confirmed,'مؤكد','var(--green)'],[m.cancelled,'ملغي','var(--red)'],[m.follow,'متابعة بشرية','#dba558']].map(x=>`<div><i style="background:${x[2]}"></i><span>${x[1]}</span><strong>${x[0]}</strong></div>`).join('');$('#savedAmount').textContent=`${(m.cancelled*28).toLocaleString('ar-SA')} ر.س`;$('#pilotUsed').textContent=m.attempted;$('#pilotProgress').style.width=`${Math.min(m.attempted/50*100,100)}%`}
function orderRow(o,actions=false){return `<tr><td><strong>${escapeHtml(o.id)}</strong></td><td>${escapeHtml(o.customer)}</td>${actions?`<td dir="ltr">${escapeHtml(o.phone)}</td>`:''}<td>${Number(o.value).toLocaleString('ar-SA')} ر.س</td><td>${statusBadge(o.status)}</td><td>${actions?`<button class="row-action" data-call="${escapeHtml(o.id)}">${o.status==='queued'?'بدء المحاكاة':'عرض النتيجة'}</button>`:escapeHtml(o.updated)}</td></tr>`}
function renderRecent(){$('#recentOrders').innerHTML=orders.slice(0,5).map(o=>orderRow(o)).join('')}
function renderOrders(){const q=$('#searchInput').value.trim().toLowerCase(),filter=$('#statusFilter').value;const visible=orders.filter(o=>(filter==='all'||o.status===filter)&&(!q||`${o.id} ${o.customer} ${o.phone}`.toLowerCase().includes(q)));$('#ordersTable').innerHTML=visible.map(o=>orderRow(o,true)).join('');$('#emptyState').hidden=visible.length>0;$$('[data-call]').forEach(b=>b.addEventListener('click',()=>{selectedOrderId=b.dataset.call;setView('calls');selectCall(selectedOrderId)}))}
function renderQueue(){const queue=orders.filter(o=>o.status==='queued'||o.status==='calling');$('#queueCount').textContent=queue.length;$('#callQueue').innerHTML=queue.length?queue.map(o=>`<div class="queue-item ${o.id===selectedOrderId?'selected':''}" data-select-call="${escapeHtml(o.id)}"><div><strong>${escapeHtml(o.customer)}</strong><small>${escapeHtml(o.id)} · ${Number(o.value).toLocaleString('ar-SA')} ر.س</small></div><button>اتصال</button></div>`).join(''):'<div class="empty"><span>✓</span><h3>قائمة الانتظار فارغة</h3><p>استورد طلبات جديدة لبدء تجربة أخرى.</p></div>';$$('[data-select-call]').forEach(x=>x.addEventListener('click',()=>selectCall(x.dataset.selectCall)))}
function selectCall(id){selectedOrderId=id;const o=orders.find(x=>x.id===id);if(!o)return;$('#callCustomer').textContent=o.customer;$('#callMeta').textContent=`${o.id} · ${o.phone} · ${Number(o.value).toLocaleString('ar-SA')} ر.س`;$('#playAudio').disabled=false;$$('[data-outcome]').forEach(b=>b.disabled=false);renderQueue()}
$('#playAudio').addEventListener('click',async()=>{const audio=$('#callAudio');try{await audio.play();$('.phone-visual').classList.add('active');$('#playAudio').textContent='◼ الرسالة قيد التشغيل';const o=orders.find(x=>x.id===selectedOrderId);if(o){o.status='calling';o.attempts=Math.max(o.attempts,1);o.updated='الآن';saveOrders();renderAll()}audio.onended=()=>{$('.phone-visual').classList.remove('active');$('#playAudio').textContent='↻ إعادة تشغيل الرسالة'}}catch{toast('تعذر تشغيل الملف الصوتي. تحقق من إعدادات المتصفح.')}});
$$('[data-outcome]').forEach(b=>b.addEventListener('click',()=>{const o=orders.find(x=>x.id===selectedOrderId);if(!o)return;o.status=b.dataset.outcome;o.attempts=Math.max(o.attempts,1);o.updated='الآن';saveOrders();toast(`تم حفظ النتيجة: ${labels[o.status]}`);selectedOrderId=null;$('#callCustomer').textContent='تم حفظ نتيجة المكالمة';$('#callMeta').textContent='اختر الطلب التالي من قائمة الانتظار.';$('#playAudio').disabled=true;$$('[data-outcome]').forEach(x=>x.disabled=true);renderAll()}));
$('#searchInput').addEventListener('input',renderOrders);$('#statusFilter').addEventListener('change',renderOrders);
$('#csvInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const lines=(await file.text()).replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2){toast('ملف CSV فارغ أو غير صالح.');return}const headers=splitCsv(lines[0]).map(x=>x.trim().toLowerCase());const get=(row,names)=>{const i=names.map(n=>headers.indexOf(n)).find(i=>i>=0);return i>=0?row[i]:''};const imported=lines.slice(1).map((line,i)=>{const row=splitCsv(line);return{id:get(row,['id','order_id','order'])||`CSV-${Date.now()}-${i+1}`,customer:get(row,['customer','name','customer_name'])||'عميل جديد',phone:get(row,['phone','mobile','telephone'])||'غير متوفر',value:Number(get(row,['value','amount','total']))||0,status:'queued',updated:'الآن',attempts:0}});orders=[...imported,...orders];saveOrders();e.target.value='';renderAll();toast(`تم استيراد ${imported.length} طلب بنجاح.`)});
$('#exportBtn').addEventListener('click',()=>{const rows=[['order_id','customer','phone','value_sar','status','attempts'],...orders.map(o=>[o.id,o.customer,o.phone,o.value,o.status,o.attempts])];const csv='\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`mujeeb-results-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);toast('تم تجهيز ملف النتائج.')});
function splitCsv(line){const out=[];let cur='',quote=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){cur+='"';i++}else if(c==='"')quote=!quote;else if(c===','&&!quote){out.push(cur);cur=''}else cur+=c}out.push(cur);return out}
function csvCell(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function renderAll(){renderMetrics();renderRecent();renderOrders();renderQueue()}
renderAll();
