import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {
  BarChart3, Boxes, CheckCircle2, Clipboard, Code2, CreditCard, Link2,
  LockKeyhole, LogOut, MessageCircle, PackageCheck, ShieldCheck, Sparkles,
  TriangleAlert,
} from "lucide-react";
import {api} from "./api";
import type {Order, Summary, User} from "./types";

const statusLabel: Record<string,string> = {
  pending:"جديد", awaiting_customer:"بانتظار العميل", confirmed:"مؤكد",
  cancelled:"ملغي", human_follow_up:"متابعة بشرية", shipped:"تم الشحن",
  delivered:"تم التسليم", returned:"مرتجع",
};

function Auth({onDone}:{onDone:()=>void}) {
  const [mode,setMode]=useState<"login"|"register">("login");
  const [error,setError]=useState("");
  const submit=async(e:React.FormEvent<HTMLFormElement>)=>{
    e.preventDefault(); setError("");
    try { await api.post(`/api/auth/${mode}`,Object.fromEntries(new FormData(e.currentTarget))); onDone(); }
    catch(err:any){ setError(err.response?.data?.detail||"تعذر إكمال الطلب"); }
  };
  return <main className="mesh min-h-screen grid place-items-center p-5"><section className="glass w-full max-w-5xl overflow-hidden rounded-[2rem] shadow-2xl shadow-slate-900/10 grid lg:grid-cols-2">
    <div className="bg-ink p-10 text-white min-h-[520px] flex flex-col justify-between"><div><div className="text-3xl font-black">مُجيب <span className="text-mint">Mujeeb</span></div><p className="mt-5 text-4xl font-black leading-tight">حوّل واتساب إلى<br/>محرك إيرادات لمتجرك.</p><p className="mt-5 text-slate-300 leading-7">تأكيد الطلبات، حماية الدفع عند الاستلام، واستعادة المبيعات — من لوحة واحدة.</p></div><div className="grid grid-cols-3 gap-3 text-center text-xs"><span className="rounded-xl bg-white/5 p-3">Salla</span><span className="rounded-xl bg-white/5 p-3">Zid</span><span className="rounded-xl bg-white/5 p-3">Custom API</span></div></div>
    <form onSubmit={submit} className="p-8 lg:p-12 flex flex-col justify-center"><p className="text-sm font-bold text-sky">نسخة المؤسسين التجريبية</p><h1 className="text-3xl font-black mt-2">{mode==="login"?"مرحباً بعودتك":"ابدأ بناء نظامك"}</h1><p className="text-slate-500 mt-2">أول 50 طلباً للاختبار، بلا بطاقة بنكية.</p><div className="grid gap-3 mt-7">
      {mode==="register"&&<><input name="full_name" required placeholder="الاسم الكامل" className="rounded-xl border border-slate-200 p-3"/><input name="phone" required placeholder="+9665xxxxxxxx" dir="ltr" className="rounded-xl border border-slate-200 p-3"/><input name="store_name" required placeholder="اسم المتجر" className="rounded-xl border border-slate-200 p-3"/><div className="grid grid-cols-2 gap-3"><select name="platform" className="rounded-xl border border-slate-200 p-3"><option value="salla">سلة</option><option value="zid">زد</option><option value="shopify">Shopify</option><option value="custom">متجر مخصص</option></select><select name="country_code" className="rounded-xl border border-slate-200 p-3"><option value="SA">السعودية</option><option value="AE">الإمارات</option><option value="KW">الكويت</option><option value="QA">قطر</option><option value="BH">البحرين</option><option value="OM">عُمان</option></select></div></>}
      <input name="email" type="email" required placeholder="البريد الإلكتروني" dir="ltr" className="rounded-xl border border-slate-200 p-3"/><input name="password" type="password" minLength={10} required placeholder="كلمة المرور" dir="ltr" className="rounded-xl border border-slate-200 p-3"/>{error&&<p className="text-red-600 text-sm">{error}</p>}<button className="rounded-xl bg-sky text-white font-black p-3 hover:bg-blue-700">{mode==="login"?"دخول آمن":"إنشاء الحساب"}</button></div>
      <button type="button" onClick={()=>setMode(mode==="login"?"register":"login")} className="mt-5 text-sm text-slate-600">{mode==="login"?"متجر جديد؟ أنشئ حسابك":"لديك حساب؟ سجّل الدخول"}</button>
    </form></section></main>;
}

function Stat({title,value,detail,icon:Icon,tone}:{title:string;value:string|number;detail:string;icon:any;tone:string}) {
  return <article className="glass rounded-2xl p-5"><div className="flex justify-between"><div><p className="text-sm text-slate-500">{title}</p><p className="text-3xl font-black mt-2">{value}</p></div><div className={`w-11 h-11 rounded-xl grid place-items-center ${tone}`}><Icon size={21}/></div></div><p className="text-xs text-slate-500 mt-4">{detail}</p></article>;
}

function DeveloperApi({storeId}:{storeId:string}) {
  const [createdKey,setCreatedKey]=useState(""); const [message,setMessage]=useState("");
  const keys=useQuery({queryKey:["api-keys",storeId],queryFn:async()=> (await api.get("/api/api-keys",{params:{store_id:storeId}})).data});
  const generate=async()=>{const r=await api.post("/api/api-keys",{store_id:storeId,name:"Pilot integration"});setCreatedKey(r.data.api_key);setMessage("انسخ المفتاح الآن. لن نعرضه كاملاً مرة أخرى.");keys.refetch();};
  const snippet=`curl -X POST https://api.usemujeeb.com/api/orders/custom \\\n+  -H "Content-Type: application/json" \\\n+  -H "X-Mujeeb-API-Key: YOUR_KEY" \\\n+  -d '{"order_id":"1001","customer_name":"Customer","customer_phone":"+966501234567","amount":250,"currency":"SAR","payment_method":"COD","items":[]}'`;
  return <section className="mt-8 max-w-4xl"><div className="flex items-center gap-3"><Code2 className="text-sky"/><div><h2 className="text-xl font-black">تكامل API للمتاجر</h2><p className="text-sm text-slate-500">Shopify، WooCommerce، Laravel وأي متجر مخصص.</p></div></div>
    <div className="grid lg:grid-cols-2 gap-5 mt-5"><article className="glass rounded-2xl p-6"><h3 className="font-black">مفتاح المتجر</h3><p className="text-sm text-slate-500 mt-2">يُحفظ المفتاح مشفراً كبصمة، ويمكن إلغاؤه في أي وقت.</p>{createdKey?<><div dir="ltr" className="mt-4 break-all rounded-xl bg-slate-950 p-4 text-xs text-emerald-300">{createdKey}</div><button onClick={()=>navigator.clipboard.writeText(createdKey)} className="mt-3 flex items-center gap-2 text-sky font-bold"><Clipboard size={16}/> نسخ المفتاح</button></>:<button onClick={generate} className="mt-5 rounded-xl bg-ink text-white px-5 py-3 font-bold">إنشاء مفتاح API</button>}{message&&<p className="mt-3 text-xs text-amber-700">{message}</p>}<p className="mt-5 text-xs text-slate-500">المفاتيح النشطة: {keys.data?.length||0}</p></article>
    <article className="glass rounded-2xl p-6"><h3 className="font-black">أرسل أول طلب</h3><pre dir="ltr" className="mt-4 overflow-auto rounded-xl bg-slate-950 p-4 text-[11px] leading-5 text-slate-200">{snippet}</pre><button onClick={()=>navigator.clipboard.writeText(snippet)} className="mt-3 flex items-center gap-2 text-sky font-bold"><Clipboard size={16}/> نسخ المثال</button></article></div></section>;
}

function Dashboard({user,onLogout}:{user:User;onLogout:()=>void}) {
  const store=user.stores[0]; const [tab,setTab]=useState("overview");
  const summary=useQuery({queryKey:["summary",store.id],queryFn:async()=> (await api.get<Summary>("/api/orders/summary",{params:{store_id:store.id}})).data});
  const orders=useQuery({queryKey:["orders",store.id],queryFn:async()=> (await api.get<Order[]>("/api/orders",{params:{store_id:store.id}})).data});
  const connect=(provider:"salla"|"zid")=>api.post(`/api/integrations/${provider}/start`,{store_id:store.id}).then(r=>location.href=r.data.url);
  const s=summary.data||{total:0,confirmed:0,cancelled:0,human_follow_up:0,confirmation_rate:0};
  const nav=[{id:"overview",label:"نظرة عامة",icon:BarChart3},{id:"orders",label:"الطلبات",icon:Boxes},{id:"integrations",label:"الربط",icon:Link2},{id:"developer",label:"API المتجر",icon:Code2},{id:"billing",label:"الباقة",icon:CreditCard}];
  return <div className="min-h-screen lg:grid lg:grid-cols-[240px_1fr]" dir="rtl"><aside className="bg-ink text-white p-5 lg:min-h-screen"><div className="text-2xl font-black mb-8">مُجيب <span className="text-mint">M</span></div><nav className="flex lg:flex-col gap-2 overflow-auto">{nav.map(n=><button key={n.id} onClick={()=>setTab(n.id)} className={`flex items-center gap-3 rounded-xl px-4 py-3 whitespace-nowrap ${tab===n.id?"bg-white text-ink":"text-slate-300 hover:bg-white/10"}`}><n.icon size={18}/>{n.label}</button>)}</nav><button onClick={onLogout} className="mt-8 lg:mt-[45vh] flex gap-2 text-slate-400"><LogOut size={18}/> خروج</button></aside>
  <main className="mesh p-5 lg:p-8"><header className="flex justify-between items-center"><div><p className="text-sm text-slate-500">{store.name} · {store.country_code}</p><h1 className="text-2xl font-black mt-1">أهلاً، {user.full_name.split(" ")[0]}</h1></div><span className="rounded-full bg-emerald-100 text-emerald-800 px-3 py-1 text-xs font-bold">الخطة المجانية</span></header>
  {tab==="overview"&&<><section className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mt-8"><Stat title="إجمالي الطلبات" value={s.total} detail="هذا الشهر" icon={PackageCheck} tone="bg-blue-100 text-blue-700"/><Stat title="طلبات مؤكدة" value={s.confirmed} detail={`${s.confirmation_rate}% معدل التأكيد`} icon={CheckCircle2} tone="bg-emerald-100 text-emerald-700"/><Stat title="تحتاج متابعة" value={s.human_follow_up} detail="أولوية فريقك" icon={TriangleAlert} tone="bg-amber-100 text-amber-700"/><Stat title="طلبات ملغاة" value={s.cancelled} detail="راجع أسباب الرفض" icon={ShieldCheck} tone="bg-rose-100 text-rose-700"/></section><section className="glass rounded-2xl p-6 mt-5"><div className="flex justify-between"><div><h2 className="font-black text-lg">مركز العمل اليومي</h2><p className="text-sm text-slate-500 mt-1">ابدأ بالطلبات الأعلى مخاطرة، ثم تابع الحالات غير المحسومة.</p></div><Sparkles className="text-sky"/></div><div className="mt-6 rounded-xl bg-ink text-white p-5 flex flex-wrap justify-between gap-4"><div><p className="text-sm text-slate-300">الخطوة التالية</p><p className="font-bold mt-1">اربط متجرك، ثم يفعّل فريق مجيب رقم واتساب التجريبي لك.</p></div><button onClick={()=>setTab("integrations")} className="rounded-xl bg-mint px-5 py-2 font-bold">ابدأ الربط</button></div></section></>}
  {tab==="orders"&&<section className="glass rounded-2xl p-5 mt-8 overflow-auto"><h2 className="text-xl font-black mb-5">الطلبات</h2>{orders.isLoading?<p>جاري التحميل…</p>:orders.data?.length?<table className="w-full text-sm"><thead className="text-slate-500"><tr><th className="text-right p-3">الطلب</th><th>القيمة</th><th>الحالة</th><th>المخاطرة</th><th>التاريخ</th></tr></thead><tbody>{orders.data.map(o=><tr key={o.id} className="border-t border-slate-100"><td className="p-3 font-bold">#{o.external_order_number||o.id.slice(0,8)}</td><td className="text-center">{o.amount} {o.currency}</td><td className="text-center">{statusLabel[o.status]||o.status}</td><td className="text-center"><span className={`rounded-full px-2 py-1 text-xs ${o.risk_level==="high"?"bg-red-100 text-red-700":o.risk_level==="medium"?"bg-amber-100 text-amber-700":"bg-emerald-100 text-emerald-700"}`}>{o.risk_score}/100</span></td><td className="text-center text-slate-500">{new Date(o.created_at).toLocaleDateString("ar-SA")}</td></tr>)}</tbody></table>:<p className="py-16 text-center text-slate-500">ستظهر الطلبات هنا بعد ربط المنصة أو إرسال أول طلب عبر API.</p>}</section>}
  {tab==="integrations"&&<section className="mt-8"><h2 className="text-xl font-black">اربط منظومة البيع</h2><p className="text-slate-500 mt-1">نبدأ بالمتجر. فريق مجيب يدير قناة واتساب التجريبية خلال مرحلة المؤسسين.</p><div className="grid md:grid-cols-3 gap-4 mt-5">{[["سلة","استيراد الطلبات وإرجاع الحالة",()=>connect("salla")],["زد","مزامنة الطلبات والعملاء",()=>connect("zid")]].map(([name,desc,fn]:any)=><article className="glass rounded-2xl p-6" key={name}><Link2 className="text-mint"/><h3 className="font-black text-lg mt-5">{name}</h3><p className="text-sm text-slate-500 mt-2 min-h-10">{desc}</p><button onClick={fn} className="mt-5 w-full rounded-xl border border-sky text-sky p-2 font-bold hover:bg-blue-50">ربط آمن</button></article>)}<article className="glass rounded-2xl p-6"><MessageCircle className="text-mint"/><h3 className="font-black text-lg mt-5">WhatsApp Pilot</h3><p className="text-sm text-slate-500 mt-2 min-h-10">رقم مجيب المُدار لأول 50 طلباً. ربط رقم العميل الذاتي ينتظر اعتماد Meta.</p><button disabled className="mt-5 w-full rounded-xl bg-slate-100 text-slate-500 p-2 font-bold flex items-center justify-center gap-2"><LockKeyhole size={16}/> يُفعّل بواسطة فريق مجيب</button></article></div></section>}
  {tab==="developer"&&<DeveloperApi storeId={store.id}/>} 
  {tab==="billing"&&<section className="glass rounded-2xl p-6 mt-8 max-w-2xl"><p className="text-sm font-bold text-sky">باقة المؤسسين</p><h2 className="text-3xl font-black mt-2">ابدأ مجاناً، وادفع بعد تحقق القيمة.</h2><p className="text-slate-500 mt-3">الترقية عبر صفحة Creem الآمنة. لا نخزن بيانات بطاقتك.</p><button onClick={async()=>{const r=await api.post("/api/payments/checkout",{store_id:store.id,plan:"starter"});location.href=r.data.url}} className="mt-6 rounded-xl bg-ink text-white px-6 py-3 font-bold">اختيار Starter</button></section>}
  </main></div>;
}

export default function App(){const me=useQuery({queryKey:["me"],queryFn:async()=> (await api.get<User>("/api/auth/me")).data,retry:false});if(me.isLoading)return <div className="min-h-screen grid place-items-center font-black">مُجيب</div>;if(!me.data)return <Auth onDone={()=>me.refetch()}/>;return <Dashboard user={me.data} onLogout={async()=>{await api.post("/api/auth/logout");location.reload();}}/>;}
